var vibe = [
	'80s style',
	'90s babe style',
	'playboy house style',
	'opposit sex dress up',
	'weirdo style',
	'glamour',
	'beach style',
	'with wigs',
	'swagalishious style',
	'victorian style',
	'italian style',
	'french style',
	'hippie style',
	'japanese style',
	'british style',
	'disco style',
	'furcoats',
	'talk with sexy voice',
	'nazi style',
	'berlin style',
	'miami style',
	'hawaii style',
	'anime club',
	'sc8er style',
	'heroin chic style',
	'burning man style',
	'mad max style',
	'50s housewives style',
	'tin foil hats',
	'futuristic style',
	'camp style',
	'animal style'

]

function newVibe() {
		var randomNumber = Math.floor(Math.random() * (vibe.length));
		document.getElementById('vibeDisplay').innerHTML = vibe[randomNumber];
	}
	
var activity = [
	'yoga',
	'yin yoga',
	'dance',
	'arms workout',
	'bootie workout',
	'core workout',
	'aerobics',
	'massage',
	'cookies',
	'cake',
	'poetry reading',
	'fiction club',
	'figure drawing',
	'breathwork',
	'guided meditation',
	'self-forgiving meditation',
	'wumb meditation',
	'women circle',
	'men circle',
	'dynamic meditation',
	'singing',
	'board games',
	'beauty salon',
	'tea party',
	'picnic',
	'24 hour fast',
	'book reading',
	'breakdance',
	'qigun',
	'ask questions',
	'sex',
	'movie night',
	'body scan meditation',
	'orgy',
	'cleaning',
	'jam',
	'costume',
	'cuddle puddle',
	'water baloon fight',
	'bdsm',
	'ritual',
	'christmas party',
	'summon demon',
	'salt doe sculpting',
	'smile competition',
	'bar hopping',
	'call mom',
	'call a friend',
	'poker/card games',
	'swim in the lake',
	'6 mile hike',
	'shoot bb gun',
	'bbq',
	'play charades',
	'spa',
	'3 mile hike',
	'slow hike',
	'brainstorm',
	'discussion on taboo topic'
]
function newActivity() {
		var randomNumber = Math.floor(Math.random() * (activity.length));
		document.getElementById('activityDisplay').innerHTML = activity[randomNumber];
	}

var drugs = [
	'1',
	'mdma',
	'extasy',
	'k',
	'joint',
	'bong',
	'vodnik',
	'coffee',
	'green tea',
	'ghb',
	'red wine',
	'white wine',
	'tequila',
	'hard liquior',
	'high on life',
	'sugar',
	'ice cream',
	'lsd',
	'mushrooms',
	'shroom chocolate',
	'cacao',
	'dmt',
	'chamomile tea',
	'beer',
	'1 edible',
	'2 edibles',
	'3 edibles',
	'salvia',
	'whipped cream',
	'kratom',
	'microdosing'
]

function newDrugs() {
		var randomNumber = Math.floor(Math.random() * (drugs.length));
		document.getElementById('drugsDisplay').innerHTML = drugs[randomNumber];
	}
